eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 5000

spring:
  application:
    name: service-zuul


zuul:
  routes:
    hiapi:
      path: /hiapi/**
      #serviceId: eureka-client
      serviceId: hiapi-v1 #用serviceId配置负载均衡列表
      #url: http://localhost:8762
    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon-client
    feignapi:
      path: /feignapi/**
      serviceId: eureka-feign-client
  #prefix: /v1

hiapi-v1:
  ribbon:
    listOfServers: http://localhost:8762,http://localhost:8763

ribbon:
  eureka:
    enabled: false

